version: "3.9"

services: 
  web:
    build: .

    command: ./run.sh

    volumes: 
      - .:/flask_parser

    ports: 
      - "5000:5000"

  celery:
    build: .

    ports:
      - "5555:5555"

    command: celery -A tasks_parser worker -B --loglevel=INFO

    volumes: 
      - .:/flask_parser
    
    depends_on:
      - redis
    
  redis:
    image: redis
    
    ports:
        - "6370:6379"